/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AlertType } from "./components/sharpen-alert/sharpen-alert";
import { CardBorder, CardPadding } from "./components/sharpen-card/sharpen-card";
export { AlertType } from "./components/sharpen-alert/sharpen-alert";
export { CardBorder, CardPadding } from "./components/sharpen-card/sharpen-card";
export namespace Components {
    interface SharpenAlert {
        /**
          * The alert heading
         */
        "heading": string;
        /**
          * Icon
         */
        "icon": string;
        /**
          * Alert type
         */
        "type": AlertType;
    }
    interface SharpenCard {
        /**
          * Border style
         */
        "border": CardBorder;
        /**
          * Padding size
         */
        "padding": CardPadding;
    }
    interface SharpenEmpty {
    }
    interface SharpenNavLink {
        "href": string;
        "icon": string;
        "name": string;
        "selected": boolean;
    }
    interface SharpenPageNavigation {
    }
    interface SharpenPrimaryNavigation {
        /**
          * Border style
         */
        "currentUser": string;
    }
    interface SharpenProfileCard {
        "buttonText": string;
        "initial": string;
        "name": string;
        "url": string;
    }
}
declare global {
    interface HTMLSharpenAlertElement extends Components.SharpenAlert, HTMLStencilElement {
    }
    var HTMLSharpenAlertElement: {
        prototype: HTMLSharpenAlertElement;
        new (): HTMLSharpenAlertElement;
    };
    interface HTMLSharpenCardElement extends Components.SharpenCard, HTMLStencilElement {
    }
    var HTMLSharpenCardElement: {
        prototype: HTMLSharpenCardElement;
        new (): HTMLSharpenCardElement;
    };
    interface HTMLSharpenEmptyElement extends Components.SharpenEmpty, HTMLStencilElement {
    }
    var HTMLSharpenEmptyElement: {
        prototype: HTMLSharpenEmptyElement;
        new (): HTMLSharpenEmptyElement;
    };
    interface HTMLSharpenNavLinkElement extends Components.SharpenNavLink, HTMLStencilElement {
    }
    var HTMLSharpenNavLinkElement: {
        prototype: HTMLSharpenNavLinkElement;
        new (): HTMLSharpenNavLinkElement;
    };
    interface HTMLSharpenPageNavigationElement extends Components.SharpenPageNavigation, HTMLStencilElement {
    }
    var HTMLSharpenPageNavigationElement: {
        prototype: HTMLSharpenPageNavigationElement;
        new (): HTMLSharpenPageNavigationElement;
    };
    interface HTMLSharpenPrimaryNavigationElement extends Components.SharpenPrimaryNavigation, HTMLStencilElement {
    }
    var HTMLSharpenPrimaryNavigationElement: {
        prototype: HTMLSharpenPrimaryNavigationElement;
        new (): HTMLSharpenPrimaryNavigationElement;
    };
    interface HTMLSharpenProfileCardElement extends Components.SharpenProfileCard, HTMLStencilElement {
    }
    var HTMLSharpenProfileCardElement: {
        prototype: HTMLSharpenProfileCardElement;
        new (): HTMLSharpenProfileCardElement;
    };
    interface HTMLElementTagNameMap {
        "sharpen-alert": HTMLSharpenAlertElement;
        "sharpen-card": HTMLSharpenCardElement;
        "sharpen-empty": HTMLSharpenEmptyElement;
        "sharpen-nav-link": HTMLSharpenNavLinkElement;
        "sharpen-page-navigation": HTMLSharpenPageNavigationElement;
        "sharpen-primary-navigation": HTMLSharpenPrimaryNavigationElement;
        "sharpen-profile-card": HTMLSharpenProfileCardElement;
    }
}
declare namespace LocalJSX {
    interface SharpenAlert {
        /**
          * The alert heading
         */
        "heading"?: string;
        /**
          * Icon
         */
        "icon"?: string;
        /**
          * Alert type
         */
        "type": AlertType;
    }
    interface SharpenCard {
        /**
          * Border style
         */
        "border"?: CardBorder;
        /**
          * Padding size
         */
        "padding"?: CardPadding;
    }
    interface SharpenEmpty {
    }
    interface SharpenNavLink {
        "href"?: string;
        "icon"?: string;
        "name"?: string;
        "selected"?: boolean;
    }
    interface SharpenPageNavigation {
    }
    interface SharpenPrimaryNavigation {
        /**
          * Border style
         */
        "currentUser"?: string;
    }
    interface SharpenProfileCard {
        "buttonText"?: string;
        "initial": string;
        "name": string;
        "url": string;
    }
    interface IntrinsicElements {
        "sharpen-alert": SharpenAlert;
        "sharpen-card": SharpenCard;
        "sharpen-empty": SharpenEmpty;
        "sharpen-nav-link": SharpenNavLink;
        "sharpen-page-navigation": SharpenPageNavigation;
        "sharpen-primary-navigation": SharpenPrimaryNavigation;
        "sharpen-profile-card": SharpenProfileCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sharpen-alert": LocalJSX.SharpenAlert & JSXBase.HTMLAttributes<HTMLSharpenAlertElement>;
            "sharpen-card": LocalJSX.SharpenCard & JSXBase.HTMLAttributes<HTMLSharpenCardElement>;
            "sharpen-empty": LocalJSX.SharpenEmpty & JSXBase.HTMLAttributes<HTMLSharpenEmptyElement>;
            "sharpen-nav-link": LocalJSX.SharpenNavLink & JSXBase.HTMLAttributes<HTMLSharpenNavLinkElement>;
            "sharpen-page-navigation": LocalJSX.SharpenPageNavigation & JSXBase.HTMLAttributes<HTMLSharpenPageNavigationElement>;
            "sharpen-primary-navigation": LocalJSX.SharpenPrimaryNavigation & JSXBase.HTMLAttributes<HTMLSharpenPrimaryNavigationElement>;
            "sharpen-profile-card": LocalJSX.SharpenProfileCard & JSXBase.HTMLAttributes<HTMLSharpenProfileCardElement>;
        }
    }
}
