/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardBorder, CardPadding } from "./components/sharpen-card/sharpen-card";
export { CardBorder, CardPadding } from "./components/sharpen-card/sharpen-card";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SharpenCard {
        /**
          * Border style
         */
        "border": CardBorder;
        /**
          * Padding size
         */
        "padding": CardPadding;
    }
    interface SharpenNavLink {
        "href": string;
        "icon": string;
        "name": string;
        "selected": boolean;
    }
    interface SharpenPageNavigation {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSharpenCardElement extends Components.SharpenCard, HTMLStencilElement {
    }
    var HTMLSharpenCardElement: {
        prototype: HTMLSharpenCardElement;
        new (): HTMLSharpenCardElement;
    };
    interface HTMLSharpenNavLinkElement extends Components.SharpenNavLink, HTMLStencilElement {
    }
    var HTMLSharpenNavLinkElement: {
        prototype: HTMLSharpenNavLinkElement;
        new (): HTMLSharpenNavLinkElement;
    };
    interface HTMLSharpenPageNavigationElement extends Components.SharpenPageNavigation, HTMLStencilElement {
    }
    var HTMLSharpenPageNavigationElement: {
        prototype: HTMLSharpenPageNavigationElement;
        new (): HTMLSharpenPageNavigationElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sharpen-card": HTMLSharpenCardElement;
        "sharpen-nav-link": HTMLSharpenNavLinkElement;
        "sharpen-page-navigation": HTMLSharpenPageNavigationElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SharpenCard {
        /**
          * Border style
         */
        "border"?: CardBorder;
        /**
          * Padding size
         */
        "padding"?: CardPadding;
    }
    interface SharpenNavLink {
        "href"?: string;
        "icon"?: string;
        "name"?: string;
        "selected"?: boolean;
    }
    interface SharpenPageNavigation {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sharpen-card": SharpenCard;
        "sharpen-nav-link": SharpenNavLink;
        "sharpen-page-navigation": SharpenPageNavigation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sharpen-card": LocalJSX.SharpenCard & JSXBase.HTMLAttributes<HTMLSharpenCardElement>;
            "sharpen-nav-link": LocalJSX.SharpenNavLink & JSXBase.HTMLAttributes<HTMLSharpenNavLinkElement>;
            "sharpen-page-navigation": LocalJSX.SharpenPageNavigation & JSXBase.HTMLAttributes<HTMLSharpenPageNavigationElement>;
        }
    }
}
