# .github/workflows/deploy-storybook-pages.yml

name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build
      run: |
        npm ci
        npm run build-storybook
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: storybook-static

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          token: ${{ github.token }}
